name: 'Copy and replace tokens'
description: 'Copy a file and replace tokens'
author: 'BlobDevelopment'
inputs:
  source:
    description: 'Source file'
    required: true
  target:
    description: 'Target file'
    required: false

runs:
  using: 'node16'
  main: 'lib/index.js'
